"""add steam_api column in bots


Revision ID: 427a476cf762
Revises: 50016aa06b8f
Create Date: 2023-10-12 10:58:08.152704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '427a476cf762'
down_revision: Union[str, None] = '50016aa06b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('steam_api_key', sa.String(length=64), nullable=True))
    op.drop_index('bot_id', table_name='bots')
    op.create_unique_constraint(None, 'bots', ['steam_api_key'])
    op.drop_column('bots', 'bot_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('bot_id', mysql.VARCHAR(length=32), nullable=False))
    op.drop_constraint(None, 'bots', type_='unique')
    op.create_index('bot_id', 'bots', ['bot_id'], unique=False)
    op.drop_column('bots', 'steam_api_key')
    # ### end Alembic commands ###
